# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_descargas.ipynb.

# %% auto 0
__all__ = ['descarga_denue', 'descarga_redes', 'descarga_poligonos_ciudades', 'descarga_datos_completos']

# %% ../00_descargas.ipynb 3
import pandas as pd
import geopandas as gpd
import requests
import xml.etree.ElementTree as ET
import os
from zipfile import ZipFile
import shutil
from pathlib import Path

# %% ../00_descargas.ipynb 5
def descarga_denue(
        tipo:str='zmvm_2022' # Qué archivo vamos a descargar: ejemplo, zmvm_2022, zmvm_full, mexico_2022, mexico_full
    ) -> None:
    DOWNLOADS_PATH = "datos/descargas/"
    Path(DOWNLOADS_PATH).mkdir(parents=True, exist_ok=True)
    if tipo == 'zmvm_2022':
        fname = 'denue_2022_zmvm.gpkg'
        url = 'https://www.dropbox.com/s/cxyekc0wzzq6pc4/denue_2022_zmvm.gpkg?dl=1'
    elif tipo == 'ejemplo':
        fname = 'ejemplo_denue.gpkg'
        url = 'https://www.dropbox.com/s/670yx6un0t4sqal/ejemplo_denue.gpkg?dl=1'
    else:
        print(f'El tipo {tipo} todavía no está implementado')
        return

    if os.path.exists(DOWNLOADS_PATH + fname):
        print("El archivo ya está descargado")
    else:
        r = requests.get(url, allow_redirects=True)
        open(DOWNLOADS_PATH + fname, 'wb').write(r.content)
    


# %% ../00_descargas.ipynb 8
def descarga_redes():
    DOWNLOADS_PATH = "datos/descargas/"
    Path(DOWNLOADS_PATH).mkdir(parents=True, exist_ok=True)
    fname = 'red_zmvm.gpkg'
    if os.path.exists(DOWNLOADS_PATH + fname):
        print("El archivo ya está descargado")
    else:
        url = 'https://www.dropbox.com/s/0fq8e8v2axyxxoc/red_zmvm.gpkg?dl=1'
        r = requests.get(url, allow_redirects=True)
        open(DOWNLOADS_PATH + fname, 'wb').write(r.content)

# %% ../00_descargas.ipynb 11
def descarga_poligonos_ciudades():
    DOWNLOADS_PATH = "datos/descargas/"
    Path(DOWNLOADS_PATH).mkdir(parents=True, exist_ok=True)
    fname = 'silhuetas.shp.zip'
    if os.path.exists(DOWNLOADS_PATH + fname):
        print("El archivo ya está descargado")
    else:
        url = 'https://www.dropbox.com/s/kofmn5qws911ktg/silhueta_100_ciudades.zip?dl=1'
        r = requests.get(url, allow_redirects=True)
        open(DOWNLOADS_PATH + fname, 'wb').write(r.content)

# %% ../00_descargas.ipynb 14
def descarga_datos_completos():
    descarga_poligonos_ciudades()
    descarga_redes()
