# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_mallas.ipynb.

# %% auto 0
__all__ = ['grid_from_layer']

# %% ../01_mallas.ipynb 3
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import Polygon
import numpy as np
from .descargas import *

# %% ../01_mallas.ipynb 7
def grid_from_layer(layer: gpd.GeoDataFrame, # Capa que define la extensión espacial de la malla
                    size: float # Tamaño de los elementos de la malla (en las unidades de la proyección de `layer`)
                    ) -> gpd.GeoDataFrame:
    """ 
    Regresa un GeoDataFrame con la malla de la extensión de la capa (`layer`) que se le pase y de tamaño `size`.
    
    """
    xmin, ymin, xmax, ymax = layer.total_bounds
    cols = list(np.arange(xmin, xmax + size, size))
    rows = list(np.arange(ymin, ymax + size, size))

    polygons = []
    for x in cols[:-1]:
        for y in rows[:-1]:
            polygons.append(Polygon([(x,y), (x + size, y), (x + size, y + size), (x, y + size)]))

    grid = gpd.GeoDataFrame({'geometry':polygons}).set_crs(layer.crs)
    return grid
