project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: secondary
    logo: "logo_centrogeo.png"
    logo-href: "https://www.centrogeo.org.mx/"
    search: true
    right:
      - icon: github
        href: "https://github.com/CentroGeo/pyLandUseMX"
      - icon: twitter
        href: https://twitter.com/plablo09
        aria-label: plablo09 Twitter    
  sidebar:
    style: docked
    collapse-level: 1
    # contents: 
    #   - auto: "/*.ipynb"
    #   - section: Tutoriales
    #     contents: 
    #       - tutoriales
    #   - section: API
    #     contents: 
    #       - api

metadata-files: [nbdev.yml, sidebar.yml]